import requests

url = "http://localhost:8000/api/bot_questions/"

payload = [
    '{"category": "Age",			"text": "Umur kamu berapa?"}',
    '{"category": "Age",			"text": "Berapa umur kamu?"}',
    '{"category": "Age",			"text": "Berapa umur kamu sekarang?"}',
    '{"category": "Age",			"text": "Sekarang berapa umur kamu?"}',
    '{"category": "Age",			"text": "Tahun ini umur kamu berapa?"}',
    '{"category": "Age",			"text": "Tahun ini berapa umur kamu?"}',
    '{"category": "Age",			"text": "Tahun ini berapa umurmu?"}',
    '{"category": "Age",			"text": "Umur kamu berapa tahun ini?"}',
    '{"category": "Age",			"text": "Berapa umur kamu tahun ini?"}',
    '{"category": "Age",			"text": "Berapa umurmu tahun ini?"}',
    '{"category": "Age",			"text": "Usia kamu berapa?"}',
    '{"category": "Age",			"text": "Berapa usia kamu?"}',
    '{"category": "Age",			"text": "Berapa usia kamu sekarang?"}',
    '{"category": "Age",			"text": "Sekarang berapa usia kamu?"}',
    '{"category": "Age",			"text": "Tahun ini usia kamu berapa?"}',
    '{"category": "Age",			"text": "Tahun ini berapa usia kamu?"}',
    '{"category": "Age",			"text": "Tahun ini berapa usiamu?"}',
    '{"category": "Age",			"text": "Usia kamu berapa tahun ini?"}',
    '{"category": "Age",			"text": "Berapa usia kamu tahun ini?"}',
    '{"category": "Age",			"text": "Berapa usiamu tahun ini?"}',
    '{"category": "Degree",			"text": "Tingkat pendidikan terakhir kamu apa?"}',
    '{"category": "Degree",			"text": "Boleh tahu tingkat pendidikan terakhir kamu?"}',
    '{"category": "Degree",			"text": "Tingkat pendidikan terakhir kamu apa?"}',
    '{"category": "Degree",			"text": "Jenjang pendidikan terakhir kamu apa?"}',
    '{"category": "SkillSet",			"text": "Coba sebutkan kemampuan kamu apa saja"}',
    '{"category": "SkillSet",			"text": "Coba sebutkan skill set kamu"}',
    '{"category": "SkillSet",			"text": "Nah, aku mau tau dulu nih skill kamu apa saja"}',
    '{"category": "SkillSet",			"text": "Kamu punya kemampuan apa saja?"}',
    '{"category": "SkillSet",			"text": "Kamu punya kemampuan dan keterampilan apa saja?"}',
    '{"category": "SkillSet",			"text": "Kamu punya keterampilan apa saja?"}',
    '{"category": "SkillSet",			"text": "Menurut kamu, kamu punya skill apa saja?"}',
    '{"category": "SkillSet",			"text": "Mau tau dong skill kamu apa saja nih?"}',
    '{"category": "SkillSet",			"text": "Coba sebutkan skill yang kamu kuasai"}',
    '{"category": "SkillSet",			"text": "Boleh sebutkan salah satu skill yang kamu miliki?"}',
    '{"category": "SkillSet",			"text": "Apa skill yang kamu miliki?"}',
    '{"category": "SkillSet",			"text": "Apa keterampilan yang kamu punya?"}',
    '{"category": "SkillSet",			"text": "Skill apa yang kamu miliki?"}',
    '{"category": "Major",			"text": "Jurusan pendidikan kamu apa?"}',
    '{"category": "Major",			"text": "Kalau boleh tahu jurusan pendidikan kamu apa ya?"}',
    '{"category": "Major",			"text": "Kalau boleh tahu bidang pendidikan kamu apa ya?"}',
    '{"category": "Major",			"text": "Kamu ambil jurusan studi apa?"}',
    '{"category": "Major",			"text": "Bidang pendidikan kamu apa?"}',
    '{"category": "Major",			"text": "Bidang pendidikan apa yang kamu ambil?"}',
    '{"category": "Major",			"text": "Kamu ambil bidang pendidikan apa?"}',
    '{"category": "Major",			"text": "Kamu lulusan dari jurusan apa?"}',
    '{"category": "WorkExp",			"text": "Kamu sudah bekerja berapa bulan?"}',
    '{"category": "WorkExp",			"text": "Kamu sudah pernah bekerja berapa bulan?"}',
    '{"category": "WorkExp",			"text": "Berapa bulan kamu bekerja sebelumnya?"}',
    '{"category": "WorkExp",			"text": "Berapa bulan lamanya kamu bekerja sebelumnya?"}',
    '{"category": "WorkExp",			"text": "Sebelumnya, kamu pernah bekerja berapa bulan?"}',
    '{"category": "WorkExp",			"text": "Pengalaman kerja kamu berapa bulan?"}',
    '{"category": "WorkExp",			"text": "Berapa bulan pengalaman kerja yang kamu miliki?"}',
    '{"category": "Position",			"text": "Jabatan terakhir kamu apa?"}',
    '{"category": "Position",			"text": "Apa posisi terakhir yang kamu tempati?"}',
    '{"category": "Position",			"text": "Di tempat kerjamu sebelumnya, kamu berada pada posisi sebagai apa?"}',
    '{"category": "Position",			"text": "Apa jenjang karirmu ditempat kerja terakhir?"}',
    '{"category": "Position",			"text": "Posisi terakhirmu sebagai apa?"}',
    '{"category": "Position",			"text": "Kamu menjabat sebagai apa sebelumnya?"}',
    '{"category": "Position",			"text": "Apa jabatan terakhir yang kamu tempati?"}',
    '{"category": "Position",			"text": "Apa jabatan terakhir yang kamu dapat?"}',
    '{"category": "SalaryUpper",		"text": "Berapa gaji maksimum yang kamu inginkan?"}',
    '{"category": "SalaryLower",		"text": "Berapa minimum yang kamu inginkan?"}',
    '{"category": "SalaryUpper",		"text": "Berapa gaji maksimum yang kamu harapkan?"}',
    '{"category": "SalaryLower",		"text": "Berapa gaji minimum yang kamu harapkan?"}',
    '{"category": "SalaryUpper",		"text": "Sebutkan gaji maksimum yang kamu inginkan"}',
    '{"category": "SalaryLower",		"text": "Sebutkan gaji minimum yang kamu inginkan"}',
    '{"category": "Location",			"text": "Kamu tinggal di kota apa?"}',
    '{"category": "Location",			"text": "Kamu asal mana si?"}',
    '{"category": "Location",			"text": "Kamu berasal dari kota mana?"}',
    '{"category": "Location",			"text": "Kota domisili kamu dimana?"}',
    '{"category": "Location",			"text": "Di mana kota tempat kamu tinggal?"}',
    '{"category": "Location",			"text": "Di mana lokasi tempat tinggalmu?"}',
    '{"category": "Location",			"text": "Di mana kota tempat tinggalmu?"}',
    '{"category": "Location",			"text": "Kamu sekarang tinggal dimana?"}',
    '{"category": "Facility",			"text": "Fasilitas apa yang kamu inginkan?"}',
    '{"category": "Facility",			"text": "Fasilitas apa yang kamu butuhkan untuk menunjang pekerjaanmu?"}',
    '{"category": "Facility",			"text": "Apa jenis fasilitas yang kamu inginkan?"}',
    '{"category": "Facility",			"text": "Apa tunjangan yang kamu harapkan?"}',
    '{"category": "Facility",			"text": "Fasilitas apa saja yang kamu butuhkan?"}',
    '{"category": "Facility",			"text": "Apa saja fasilitas yang kamu butuhkan?"}',
    '{"category": "Facility",			"text": "Apa saja fasilitas yang kamu perlukan?"}',
    '{"category": "Facility",			"text": "Fasilitas apa saja yang kamu inginkan?"}',
    '{"category": "Industry",			"text": "Sekarang kamu sedang bekerja di industri apa?"}',
    '{"category": "Industry",			"text": "Sekarang kamu sedang bekerja di industri apa ya?"}',
    '{"category": "Industry",			"text": "Sekarang kamu sedang bekerja di industri apa sih?"}',
    '{"category": "Industry",			"text": "Industri tempat kamu kerja bergerak dibidang apa?"}',
    '{"category": "Industry",			"text": "Boleh tau bidang industri tempar kerjamu sekarang?"}',
    '{"category": "Industry",			"text": "Tempat kerja kamu sekarang bergerak dibidang apa sih?"}',
    '{"category": "Industry",			"text": "Tempat kerja kamu sekarang bergerak dibidang apa?"}',
    '{"category": "Field",			"text": "Bidang pekerjaan kamu apa?"}',
    '{"category": "Field",			"text": "Bidang pekerjaan kamu sekarang apa ya?"}',
    '{"category": "Field",			"text": "Sekarang bidang pekerjaan kamu apa sih?"}',
    '{"category": "Field",			"text": "Bidang pekerjaan ditempat kerjamu apa?"}',
    '{"category": "Field",			"text": "Sebutkan bidang pekerjaanmu"}',
    '{"category": "Field",			"text": "Kamu bekerja dibidang apa?"}',
    '{"category": "Field",			"text": "Apa bidang pekerjaanmu?"}',
    '{"category": "Field",			"text": "Apa bidang pekerjaanmu saat ini?"}',
    '{"category": "Field",			"text": "Apa bidang pekerjaanmu sekarang ini?"}',
    '{"category": "JobLevel",			"text": "Pangkat kamu sekarang apa sih?"}',
    '{"category": "JobLevel",			"text": "Apa pangkat kerja kamu saat ini?"}',
    '{"category": "JobLevel",			"text": "Apa pangkat kerja kamu sekarang?"}',
    '{"category": "JobLevel",			"text": "Di tempat kerja, pangkat kamu apa?"}',
    '{"category": "JobLevel",			"text": "Apa pangkat yang kamu miliki di tempat kerja?"}',
    '{"category": "JobLevel",			"text": "Apa pangkat yang kamu duduki saat ini?"}',
    '{"category": "ExpectedLocation",		"text": "Lokasi kerja manakah yang kamu inginkan?"}',
    '{"category": "ExpectedLocation",		"text": "Lokasi mana yang kamu inginkan untuk bekerja?"}',
    '{"category": "ExpectedLocation",		"text": "Di mana lokasi penempatan kerja yang kamu inginkan?"}',
    '{"category": "ExpectedLocation",		"text": "Lokasi mana yang kamu inginkan?"}',
    '{"category": "ExpectedLocation",		"text": "Lokasi manakah yang kamu inginkan utk bekerja?"}',
    '{"category": "ExpectedLocation",		"text": "Di kota manakah kamu bersedia ditempatkan?"}',
    '{"category": "FreshGraduate",		"text": "Kamu lulusan baru atau sudah pernah bekerja nih?"}',
    '{"category": "FreshGraduate",		"text": "Kalau kamu sudah pernah kerja atau baru aja lulus?"}',
    '{"category": "FreshGraduate",		"text": "Kamu sudah kerja atau baru lulus ya?"}',
    '{"category": "FreshGraduate",		"text": "Kamu sudah punya pengalaman kerja atau lulusan baru?"}',
    '{"category": "FreshGraduate",		"text": "Apa kamu lulusan baru? Atau sudah pernah bekerja sebelumnya?"}',
    '{"category": "FreshGraduate",		"text": "Mau nanya dong kamu udah kerja atau baru lulus ya?"}',
    '{"category": "FreshGraduate",		"text": "Sebelumnya kamu sudah pernah bekerja? Atau kamu lulusan baru?"}',
]
headers = {
    'Content-Type': "application/json",
    'cache-control': "no-cache",
    'Postman-Token': "9ad5e836-84cb-401e-9021-bc28552d4964"
}

for p in payload:
    print p
    response = requests.request("POST", url, data=p, headers=headers)

    print(response.text)
