# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-31 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='age',
            new_name='max_age',
        ),
        migrations.AddField(
            model_name='job',
            name='min_age',
            field=models.SmallIntegerField(default=18),
        ),
    ]
