# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-31 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20181231_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='work_exp',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
