# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-14 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20181231_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['title'], name='job_job_title_23b697_idx'),
        ),
    ]
