# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-14 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20190414_0740'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['id', 'title'], name='job_job_id_616898_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['link'], name='job_job_link_703d0c_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['link', 'title'], name='job_job_link_1fd7c1_idx'),
        ),
    ]
