# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-20 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20190414_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='original_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['original_title', 'title'], name='job_job_origina_067e30_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['original_title'], name='job_job_origina_778b3e_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['original_title', 'link'], name='job_job_origina_601032_idx'),
        ),
    ]
